# Generated by Django 3.2.8 on 2022-01-07 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220107_1313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='ProfileNmae',
            new_name='ProfileName',
        ),
    ]
